name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H edustudy-api.edustudyconsultants.com >> ~/.ssh/known_hosts

      - name: Deploy to Hostinger
        run: |
          ssh -i ~/.ssh/id_rsa u751962952@edustudy-api.edustudyconsultants.com "
            cd ~/domains/edustudyconsultants.com/edustudy-api &&
            git pull origin main &&
            composer install --no-dev --prefer-dist &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache
          "
