name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.edustudy }}" > /home/runner/.ssh/id_rsa
          echo "${{ secrets.edustudy }}" > /home/runner/.ssh/known_hosts
          chmod 600 /home/runner/.ssh/id_rsa
       

      - name: Deploy via SSH
        run: |
          ssh -p 65002 u751962952@93.127.208.205
          cd domains/edustudyconsultants.com/public_html/edustudy-api && git pull origin main && php artisan migrate --force
